Parser: ItemCard
ID: 38
StringID: FalconFigurineID
Name: $ITEM_NAME_FalconFigurine$
Art: Falcon Figurine
TotalInGame: 2
Cost: 50
Slot: SmallItem 
Rarity: Rare
Usage: Consumed
Trigger: DuringOwnTurn
ProsperityRequirement: 4
Data: 
    Abilities:
        ASummon:
            Summon: JadeFalconID
            AnimOverload: Summon
Layout:
    - Active:
        Ability: ASummon
        Icon: Summon
        Layout:
            - Summon:
                Ability: ASummon
                SummonName: "$JadeFalcon$ <sprite name=Flying>"